### ISSUE TITLE
TypeError on onSearch and setting the selected values programmatically

### ISSUE THREAD

**Issue by sabloger** [ng-select/ng-select#1902]
After upgrading Angular to v11 and ng-select to v6.1.0, I am getting this TypeError on setting the selected values programmatically and on user type in search field in console, but everything is working well!

```
core.js:6210 ERROR TypeError: Cannot set property context of [object Object] which has only a getter
    at NgTemplateOutlet.ngOnChanges (common.js:4190)
    at NgTemplateOutlet.rememberChangeHistoryAndInvokeOnChangesHook (core.js:1520)
    at callHook (core.js:2583)
    at callHooks (core.js:2542)
    at executeCheckHooks (core.js:2474)
    at refreshView (core.js:9475)
    at refreshEmbeddedViews (core.js:10591)
    at refreshView (core.js:9490)
    at refreshEmbeddedViews (core.js:10591)
    at refreshView (core.js:9490)
```

I tried many solutions but I still get this error. My simplest use of ng-select to find out the problem is like this:

```
        fooItems = [
          {id: 1, name: 'Foo'},
          {id: 2, name: 'Bar'},
          {id: 3, name: 'Baz'},
        ];
```
```
        <ng-select
          bindValue="id"
          bindLabel="name"
          [items]="fooItems"
        >
        </ng-select>
```

**Comment by sabloger** [comment]
Updating Angular to v12 has been fixed the error.
